name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    # ✅ 建議先拿掉，否則 fork 不會跑
    # if: github.repository == 'mmistakes/minimal-mi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          docs/Gemfile.lock
          docs/vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('docs/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install - Bundler
      env:
        MAKE: make -j2
      working-directory: docs/
      run: |
        bundle config set path vendor/bundle
        bundle install --jobs=4 --retry=3
        bundle clean

# ✅ 如果沒有用 Algolia，這段可以先註解或移除
    - name: Build site
      working-directory: minimal-mistakes/
      run: bundle exec jekyll build
